### ISSUE TITLE
Pathfinder 2e v5.15 does not work

### ISSUE THREAD

**Issue by kagangtuya-star** [flyingsquad/htmlfilter#1]
![image](https://github.com/flyingsquad/htmlfilter/assets/73411104/9021a4dd-8f76-4849-94d7-247feccb6eb2)

Pathfinder 2e v5.15 does not work,The printed page is blank.

The following error occurred.Both filters files do not work properly.

```
foundry.js:68326  TypeError: Cannot read properties of undefined (reading 'value')
    at pf2eObject._initialize (pf2efilter.js:160:55)
    at new SystemObject (systemobject.js:160:8)
    at new pf2eObject (pf2efilter.js:12:3)
    at HTMLFilter.filter (htmlfilter.js:845:24)
    at Object.onclick (htmlfilter.js:1014:6)
```

**Comment by kagangtuya-star** [comment]
```
// Modifying the code in pf2efilter.js on line 160 fixes the problem
//		this.defs['alignment'] = a.system.details.alignment.value;
		this.defs['alignment'] = a.system.details.alignment;

```

**Comment by flyingsquad** [comment]
Thanks for that. I've updated the file and the latest release has the fix.

**Comment by flyingsquad** [comment]
Fixed
